<a href="https://colab.research.google.com/github/donlap/stat424/blob/main/1_numpy_and_jax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
u = np.array([1, 2, 3])

v = u + 3

print(v)


[4 5 6]


In [ ]:
w = u * 3

print(w)

[3 6 9]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Matrix-vector multiplication

In [ ]:
A @ u

array([14, 32, 50])

## Function

In [ ]:
def f(x):
  return (x - 3)**2 + 1

In [ ]:
f(2)

2

In [ ]:
f = lambda x: (x - 3)**2 + 1

In [ ]:
f(2)

2

In [ ]:
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
f(x)

array([10,  5,  2,  1,  2,  5, 10, 17, 26, 37])

In [ ]:
import jax
import jax.numpy as jnp

grad_f = jax.grad(f)

grad_f

<function __main__.f(x)>

$f(x) = (x - 3)^2 + 1$, $f'(x) = 2(x - 3)$

In [ ]:
grad_f(3.0)

Array(0., dtype=float32, weak_type=True)

In [ ]:
grad_f(4.0)

Array(2., dtype=float32, weak_type=True)

## Converting JAX and numpy array

In [ ]:
B = jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B

Array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [ ]:
w = jnp.array([1, 2, 3])

B @ w

Array([14, 32, 50], dtype=int32)

In [ ]:
C = np.asarray(B)

C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [ ]:
D = jnp.array(C)

D

Array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)