<a href="https://colab.research.google.com/github/donlap/stat424/blob/main/2_gradient_and_Hessian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import jax
import jax.numpy as jnp

In [ ]:
f = lambda x: (x - 3)**2 + 1

grad_f = jax.grad(f)
grad_grad_f = jax.grad(grad_f)

grad_f(3.0)

Array(0., dtype=float32, weak_type=True)

In [ ]:
grad_grad_f(3.0)

Array(2., dtype=float32, weak_type=True)

In [ ]:
g = lambda x: x[0]**2 + 2*x[0]*x[1] + 2*x[1]**2

grad_g = jax.grad(g)

hess_g = jax.hessian(g)

In [ ]:
grad_g(jnp.array([0.0, 0.0]))

Array([0., 0.], dtype=float32)

In [ ]:
hessian_at_0 = hess_g(jnp.array([0.0, 0.0]))

In [ ]:
jnp.linalg.eigvals(hessian_at_0)

Array([0.763932+0.j, 5.236068+0.j], dtype=complex64)

In [ ]:
linear_form = lambda x, a: x @ a

grad_linear_form = jax.grad(linear_form, argnums=0)

key_a = jax.random.key(0)
key_x = jax.random.key(1)

a = jax.random.normal(key_a, (5,))
x = jax.random.normal(key_x, (5,))

print(x)
print(a)
grad_linear_form(x, a)

[-0.15443718  0.08470728 -0.13598049 -0.15503626  1.2666674 ]
[ 1.6226422   2.0252647  -0.43359444 -0.07861735  0.1760909 ]


Array([ 1.6226422 ,  2.0252647 , -0.43359444, -0.07861735,  0.1760909 ],      dtype=float32)

In [ ]:
quad_form = lambda x, A: x.T @ A @ x

grad_quad_form = jax.grad(quad_form, argnums=0)

key_a = jax.random.key(0)
key_x = jax.random.key(1)

A = jax.random.normal(key_a, (5, 5))
x = jax.random.normal(key_x, (5,))

grad_quad_form(x, A)

Array([-3.0035107 ,  0.68403363,  1.0690984 , -1.5895946 ,  0.6493838 ],      dtype=float32)

In [ ]:
(A + A.T) @ x

Array([-3.0035107 ,  0.68403375,  1.0690982 , -1.5895946 ,  0.6493838 ],      dtype=float32)