<a href="https://colab.research.google.com/github/donlap/stat424/blob/main/4_convex_program_using_CVXPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import cvxpy as cp
from sklearn.datasets import load_diabetes

In [ ]:
data = load_diabetes()
X, y = data.data, data.target
feature_names = data.feature_names

In [ ]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [ ]:
feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [ ]:
X_scaled = (X - X.mean()) / X.std()



In [ ]:
X_final = np.hstack([np.ones((X_scaled.shape[0], 1)), X_scaled])
X_final

array([[ 1.        ,  0.80050009,  1.06548848, ..., -0.05449919,
         0.41853093, -0.37098854],
       [ 1.        , -0.03956713, -0.93853666, ..., -0.83030083,
        -1.43658851, -1.93847913],
       [ 1.        ,  1.79330681,  1.06548848, ..., -0.05449919,
         0.06015558, -0.54515416],
       ...,
       [ 1.        ,  0.87686984,  1.06548848, ..., -0.23293356,
        -0.98564884,  0.32567395],
       [ 1.        , -0.9560041 , -0.93853666, ...,  0.55838411,
         0.93616291, -0.54515416],
       [ 1.        , -0.9560041 , -0.93853666, ..., -0.83030083,
        -0.08875225,  0.06442552]])

In [ ]:
d = X_final.shape[1]
lamb = 10.0

beta = cp.Variable(d)
loss = cp.sum_squares(X_final @ beta - y) / (len(y))
reg1 = lamb * cp.norm1(beta[1:])

objective = cp.Minimize(loss + reg1)
prob = cp.Problem(objective)
prob.solve()

np.float64(3678.2874326497003)

In [ ]:
beta.value

array([ 1.52133484e+02,  2.85039199e-17, -2.15540721e+00,  2.42156446e+01,
        1.03314957e+01,  1.24852265e-17,  2.19137155e-18, -7.02719498e+00,
       -1.07387353e-17,  2.12292548e+01,  5.62398597e-17])

In [ ]:
feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']